### ISSUE TITLE
Convert `TextBoxes_icdar13.caffemodel` to `TextBoxes_icdar13.mlmodel` error!

### ISSUE THREAD

**Issue by ko1o** [MhLiao/TextBoxes#49]
Hi! @MhLiao  Can you help me convert `TextBoxes_icdar13.caffemodel` to `TextBoxes_icdar13.mlmodel` through the tool `coremltools` ？
 use see: https://pypi.python.org/pypi/coremltools  extremely grateful!

I try it ：

```javascript

import coremltools
coreml_model = coremltools.converters.caffe.convert(('TextBoxes_icdar13.caffemodel',   'deploy.prototxt'))
coreml_model.save('TextBoxes_icdar13.mlmodel')

```

But I get error :

```javascript

[libprotobuf ERROR /git/coreml/deps/protobuf/src/google/protobuf/text_format.cc:298] Error parsing  text-format caffe.NetParameter: 758:14: Message type "caffe.LayerParameter" has no field named  "norm_param".
Traceback (most recent call last):
  File "convert.py", line 5, in <module>
    coreml_model = coremltools.converters.caffe.convert(('TextBoxes_icdar13.caffemodel', 'deploy.prototxt'))
  File "/Users/mambaxie/anaconda2/lib/python2.7/site-packages/coremltools/converters/caffe/_caffe_converter.py", line 142, in convert
    predicted_feature_name)
  File "/Users/mambaxie/anaconda2/lib/python2.7/site-packages/coremltools/converters/caffe/_caffe_converter.py", line 187, in _export
    predicted_feature_name
RuntimeError: Unable to load caffe network Prototxt file: deploy.prototxt
```

How do i fix it?

**Comment by prabhjot-singh-gogana** [comment]
@iphone5solo  I also getting same error Have you found any solution or any core ml model for text recognition. Thanks in advance
