### ISSUE TITLE
Hello I am a deep learning beginners, this wants to run the program to see the results, however, when running Python demo.py, the problem solving method to search on the Internet, but did not solve the problem. Please help the teacher pointed out the reason to liao. Thank you very much!

### ISSUE THREAD

**Issue by pangyanhui923** [MhLiao/TextBoxes#66]
pyh@k40-2:~/TextBoxes/examples/TextBoxes$ python demo.py
Failed `CDLL(libgeos_c.so.1)`
Failed `CDLL(libgeos_c.so)`
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from nms import nms
  File "/home/pyh/TextBoxes/examples/TextBoxes/nms.py", line 4, in <module>
    from shapely.geometry import Polygon
  File "/home/pyh/.local/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/pyh/.local/lib/python2.7/site-packages/shapely/geometry/base.py", line 9, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/pyh/.local/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/home/pyh/.local/lib/python2.7/site-packages/shapely/geos.py", line 66, in <module>
    _lgeos = load_dll('geos_c', fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
  File "/home/pyh/.local/lib/python2.7/site-packages/shapely/geos.py", line 61, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].

**Comment by dajiangxiaoyan** [comment]
apt-get install -y libgeos-dev

**Comment by pangyanhui923** [comment]
@dajiangxiaoyan Thank you!
