### ISSUE TITLE
How to retrain the network on ICDAR dataset ??

### ISSUE THREAD

**Issue by AlwaysTrying** [MhLiao/TextBoxes#78]
Hi, I need some guide to run this project... some files are messing and the documentation is not enough... How can I reproduce the same results and get 85% as F-mesure???
The file demo.py does not exist, the data of ICDAR is not in data file... is there any tutoriel I can follow plz ??

**Comment by AlwaysTrying** [comment]
@MhLiao could you provide more details and explanations plz ??

**Comment by AlwaysTrying** [comment]
is it the script train_icdar13.py that i should run to train the data and generate the model ?? 
in this file is written:
# The database file for training data. Created by data/text/create_data.sh
train_data = "path_to_train_lmdb/text_icdar_trainval_lmdb"
# The database file for testing data. Created by data/text_10x/create_data.sh
test_data = "path_to_test_lmdb/text_icdar_test_lmdb"

but there is no text in /data !!!
Am I on the wrong direction???

**Comment by MhLiao** [comment]
The data is too large. You can first generate ground truth in "xml" format, then use TextBoxes/data/VOC0712/create_data.sh to create the "lmdb" for training.

**Comment by 19931991** [comment]
Can I connect to you ,I recentlly run the code, and I want to train my own data, I hope I can talk about with you! qq:1323369151,please remark github, thanks ！@AlwaysTrying

**Comment by liuyiyiyiyi** [comment]
when i run"python examples/TextBoxes/train_icdar13.py ",the error is occured:
Traceback (most recent call last):
  File "examples/TextBoxes/train_icdar13.py", line 437, in <module>
    net[reshape_name] = L.Reshape(net[conf_name], shape=dict(dim=[0, -1, num_classes]))
  File "/home/od/dod/SaicCorNetG_v2/python/caffe/net_spec.py", line 193, in __getitem__
    return self.__getattr__(item)
  File "/home/od/dod/SaicCorNetG_v2/python/caffe/net_spec.py", line 187, in __getattr__
    return self.tops[name]
KeyError: 'mbox_conf'
